name: Example Workflow

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up variables
        run: |
          export VAR1=value1
          export VAR2=${VAR1}-suffix
          echo "VAR2=$VAR2" >> $GITHUB_ENV
      - name: Use VAR2
        run: echo "VAR2 is $VAR2"
        env:
          VAR2: ${{ env.VAR2 }}

          echo "GREETING: $GREETING"





