name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VAR1: "Hello"
      VAR2: "${{ secrets.MY_SECRET }}"
      # Using VAR1 to set another environment variable
      GREETING: "${{ env.VAR1 }}, World"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment variables
        run: |
          echo "VAR1: $VAR1"
          echo "VAR2: $VAR2"
          echo "GREETING: $GREETING"





