name: Example Workflow

on: 
  push: 
    branches: 
      - main  

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://example.com"
    steps:
      - run: |
          FULL_URL="${BASE_URL}/path"
          echo $FULL_URL

