name: Example Workflow

on: 
  push: 
    branches: 
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      FIRST_VAR: "value1"
    steps:
      - name: Define dependent environment variable
        run: echo "SECOND_VAR=${FIRST_VAR}_suffix" >> $GITHUB_ENV

      - name: Use the environment variables
        run: |
          echo "First variable is $FIRST_VAR"
          echo "Second variable is $SECOND_VAR"


